-----------------------------------------------------------------
-- Lexical LSP - below config taken from scott ming's config
-- but I don't know where to put it with astro...
-----------------------------------------------------------------
-- local lspconfig = require "lspconfig"
-- local configs = require "lspconfig.configs"
--
-- local M = {
--   cmd = { "/Users/zimakki/code/lexical-lsp/lexical/_build/dev/rel/lexical/start_lexical.sh" },
-- }
--
-- function M.load_lexical()
--   if not configs.lexical then
--     configs.lexical = {
--       default_config = {
--         filetypes = { "elixir", "eelixir", "heex", "surface" },
--         root_dir = function(fname)
--           -- Set `~/Code/lexical` as root_dir for lexical project
--           local project = lspconfig.util.root_pattern ".git"(fname)
--           if project and string.sub(project, -12) == "code/lexical" then
--             return project
--           else
--             return lspconfig.util.root_pattern("mix.exs", ".git")(fname) or vim.loop.os_homedir()
--           end
--         end,
--       },
--     }
--   end
-- end
--
-- return M
